# Problem 1

In [3]:
import numpy as np

In [34]:
x = np.ones(50)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
y

In [ ]:
absolute_sum_of_difference = np.sum(abs(z-y))
print(absolute_sum_of_difference)

In [25]:
y = np.linspace(1,20,50)
y

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [27]:
z = []
i = 1

while i < 20:
    z.append(round(i,2))
    i +=0.38
z = np.array(z)
z
# len(z)


array([ 1.  ,  1.38,  1.76,  2.14,  2.52,  2.9 ,  3.28,  3.66,  4.04,
        4.42,  4.8 ,  5.18,  5.56,  5.94,  6.32,  6.7 ,  7.08,  7.46,
        7.84,  8.22,  8.6 ,  8.98,  9.36,  9.74, 10.12, 10.5 , 10.88,
       11.26, 11.64, 12.02, 12.4 , 12.78, 13.16, 13.54, 13.92, 14.3 ,
       14.68, 15.06, 15.44, 15.82, 16.2 , 16.58, 16.96, 17.34, 17.72,
       18.1 , 18.48, 18.86, 19.24, 19.62])

# Problem 2

In [5]:
M = np.ones(1)
M

array([1.])

In [10]:

i = 0
while M[-1] !=7:
    i += 1
    
    if i > 30:
        break
    randnum = rand.rint(1,10)
    M = np.append(M,random)
    
print("\n",M,"\")
print("Length of M = ",len(M))
print()

array([9])

In [12]:
new_m = np.append (m, mrand)
new_m

array([1., 9.])

# Problem 3

In [4]:
a = np.array([  8.,3.,10.,8.,2.,2.,10.,10.,5.,10.,2.,10.,9.,10.,9.,4.,2.,8.,7.,4.,1.,4.,5.,6.,6.])

In [7]:
a = a.reshape(5,5)
k = [0,0]

for i in np.arrange(np.size(a,0)):
    for j in  np.arrange(np.size(a,1)):
        if a[]
print(f"\n Total 5's ==>{k[]} \nTotal 8's ==>{k[1]}")

[[ 8.  3. 10.  8.  2.]
 [ 2. 10. 10.  5. 10.]
 [ 2. 10.  9. 10.  9.]
 [ 4.  2.  8.  7.  4.]
 [ 1.  4.  5.  6.  6.]]


# Problem 4

In [20]:
𝐴 = np.matrix([ [1,2,3],[4,5,6],[7,8,9] ])     # 3x3 matrix
𝑥 = np.matrix([[1], [3], [4] ])      # 3x1 matrix
𝐵 = np.matrix([ [-0.1,-0.2,-0.3],[3,10,2],[4,2,0.5] ]) # 3x3 matrix
# 𝐴
# 𝑥
# 𝐵 

matrix([[-0.1, -0.2, -0.3],
        [ 3. , 10. ,  2. ],
        [ 4. ,  2. ,  0.5]])

In [22]:
A = np.array([ [1,2,3],[4,5,6],[7,8,9] ])     # 3x3 matrix
X = np.array([[1], [3], [4] ])      # 3x1 matrix
B = np.array([ [-0.1,-0.2,-0.3],[3,10,2],[4,2,0.5] ]) # 3x3 matrix
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
A_mul_B = A*B
A_mul_B

array([[-0.1, -0.4, -0.9],
       [12. , 50. , 12. ],
       [28. , 16. ,  4.5]])

In [36]:
A_Prod_B = np.dot(A,B)
A_Prod_B

array([[17.9, 25.8,  5.2],
       [38.6, 61.2, 11.8],
       [59.3, 96.6, 18.4]])

In [37]:
A_cross_B = np.cross(A,B)
A_cross_B

array([[ 1.11022302e-16, -5.55111512e-17,  0.00000000e+00],
       [-5.00000000e+01,  1.00000000e+01,  2.50000000e+01],
       [-1.40000000e+01,  3.25000000e+01, -1.80000000e+01]])

In [39]:
A_prod_X = np.dot(A,X)
A_prod_X

array([[19],
       [43],
       [67]])